### ISSUE TITLE
stats_list is keyed off of long-text description instead of the more logical hash ID

### ISSUE THREAD

**Issue by dserban** [sailthru/sailthru-python-client#52]
Hello,

This is more of a pain point related to the design of the API rather than a question. Here is a snippet from my Python REPL:
```
>>> stats = sc.stats_list(list='valid_cryptic_looking_id_of_actual_list',date='2015-03-31')
>>> stats.get_body()['error']
99
>>> stats = sc.stats_list(list='long_text_description_of_that_same_list',date='2015-03-31')
>>> stats.get_body().keys()
[u'spam_loss_count', u'passive_count', u'source_count', u'lists_remove_count', u'email_count', u'optout_loss_count', u'count_time', u'disengaged_count', u'list', u'active_count', u'lists_count', u'dormant_count', u'signup_month', u'optout_count', u'engaged_count', u'spam_count', u'lists_signup_count', u'new_count', u'day', u'hardbounce_count']
```
I can use the API as it is but this is a suboptimal setup for a non-versioned API dealing with UTF-8 content, in my opinion.

Is there a way to make the API call with the guaranteed-to-be-ASCII hash ID instead of the long-text description?

Also, would you be open to versioning the API?

**Comment by Dude-X** [comment]
As far as I know, anything related to list calls will only deal with the name of the list. The ID at this moment is only used internally. 

In the future the API will be updated to support versioning, and other nice things, but I will certainly make your request known to the organization to support list ID.

**Comment by Dude-X** [comment]
Also if you are having issues with unicode using our client, please inform  us.

**Comment by georgekliao** [comment]
@dserban can this issue be closed out?

**Comment by dserban** [comment]
Before we do that, can you at least mark this issue as wontfix or as "ASCII ID support is on the roadmap for the next release" or something else that is just as clearly defined?

For context, I'm extracting stats data from the API in order to feed it into a data warehouse for integration.
As such data quality is of the essence.
My greatest concern is that my Python client program won't be able to distinguish between "there is no data behind this combination of list_name+calendar_day" and a silent failure due to my incomplete understanding of the intricacies of Python's implementation of UTF-8.

Being able to retrieve data by ASCII ID would completely solve my problem.

Thanks and please close the issue as soon as a clear decision was made as to the roadmap issue.

**Comment by Dude-X** [comment]
http://nedbatchelder.com/blog/201203/pragmatic_unicode.html is a good guide to understand unicode.
Some main takeaways. Unicode is not UTF-8, it's the definition of characters that make up symbols, foreign letters, and so on. The way you can represent unicode characters can be encoded is via UTF-8, UTF-16, and so on. 

The problem you're having is actually related to your JSON library not being C optimized. You should make sure when you install simplejson that the C module is actually compiled. If it is not compiled, all JSON strings are converted into a dictionary that have unicode strings for all strings (which is technically correct since JSON is defined as being Unicode UTF-8). If the C module is used, only strings that have unicode strings will be proper unicode strings in Python 2 and ASCII strings are str, and thus you will avoid having to deal with string/unicode issues.

**Comment by dserban** [comment]
Thank you for taking the time to clarify.
Closing.
